create TABLE DEMO_DB_USER99.PUBLIC.SRC_ORDERS (
	ROW_ID VARCHAR,
	ORDER_ID VARCHAR,
	ORDER_DATE VARCHAR,
	SHIP_DATE VARCHAR,
	SHIP_MODE VARCHAR,
	CUSTOMER_ID VARCHAR,
	CUSTOMER_NAME VARCHAR,
	SEGMENT VARCHAR,
	COUNTRY VARCHAR,
	CITY VARCHAR,
	STATE VARCHAR,
	POSTAL_CODE VARCHAR,
	REGION VARCHAR,
	PRODUCT_ID VARCHAR,
	CATEGORY VARCHAR,
	SUB_CATEGORY VARCHAR,
	PRODUCT_NAME VARCHAR,
	SALES VARCHAR,
	QUANTITY VARCHAR,
	DISCOUNT VARCHAR,
	PROFIT VARCHAR
);
create TABLE DEMO_DB_USER99.PUBLIC.SRC_PEOPLE (
	ID NUMERIC(38,0),
	PERSON VARCHAR,
	REGION VARCHAR
);
create TABLE DEMO_DB_USER99.PUBLIC.SRC_RETURNS (
	ORDER_RETURNED VARCHAR(3),
	ORDER_ID VARCHAR
);
create TABLE DEMO_DB_USER99.PUBLIC.DIM_PEOPLE (
	ID NUMERIC(38,0),
	PERSON VARCHAR,
	REGION VARCHAR,
	INS_DT TIMESTAMP,
	UPD_DT TIMESTAMP,
	MTL_RUN_ID INTEGER
);

create TABLE DEMO_DB_USER99.PUBLIC.FILE_LOADING_INFO (
	FILE_NAME VARCHAR,
	FILE_DELIMITER VARCHAR,
	SF_TABLE_NAME VARCHAR
);

insert into DEMO_DB_USER99.public.file_loading_info values
('ORDERS.txt', '\\t','SF_ORDERS'),
('PEOPLE.txt', ',','SF_PEOPLE'),
('RETURNS.txt', '`~^','SF_RETURNS');

create TABLE DEMO_DB_USER99.PUBLIC.FACT_ORDERS (
	ROW_ID VARCHAR,
	ORDER_ID VARCHAR,
	ORDER_DATE VARCHAR,
	SHIP_DATE VARCHAR,
	SHIP_MODE VARCHAR,
	CUSTOMER_ID VARCHAR,
	CUSTOMER_NAME VARCHAR,
	SEGMENT VARCHAR,
	COUNTRY VARCHAR,
	CITY VARCHAR,
	STATE VARCHAR,
	POSTAL_CODE VARCHAR,
	REGION VARCHAR,
	PRODUCT_ID VARCHAR,
	CATEGORY VARCHAR,
	SUB_CATEGORY VARCHAR,
	PRODUCT_NAME VARCHAR,
	SALES VARCHAR,
	QUANTITY VARCHAR,
	DISCOUNT VARCHAR,
	PROFIT VARCHAR,
	INSERT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	RUN_ID NUMERIC(38,0),
	MTL_JOB_NAME VARCHAR
);

create TABLE DEMO_DB_USER99.PUBLIC.STG_DIM_PEOPLE_SCD2 (
	ID NUMERIC(38,0),
	PERSON VARCHAR,
	REGION VARCHAR,
	INDICATOR VARCHAR(1),
	V_START_DATE TIMESTAMP,
	V_END_DATE TIMESTAMP
);
create TABLE DEMO_DB_USER99.PUBLIC.DIM_PEOPLE_SCD2 (
	PEOPLE_SK INT identity(1,1),
	ID NUMERIC(38,0),
	PERSON VARCHAR,
	REGION VARCHAR,
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP
);

create TABLE DEMO_DB_USER99.PUBLIC.STG_EMP (
	"emp_no" NUMERIC(11,0),
	"first_name" VARCHAR(42),
	"gender" VARCHAR(3),
	"birth_date" DATE,
	"hire_date" DATE
);

create TABLE DEMO_DB_USER99.PUBLIC.TARGET_EMPLOYEES (
	GENDER VARCHAR(3),
	EMP_NO NUMERIC(11,0),
	BIRTH_DATE DATE,
	LAST_NAME VARCHAR(48),
	HIRE_DATE DATE,
	FIRST_NAME VARCHAR(42),
	MATILLION_BATCH_ID NUMERIC(38,0),
	MATILLION_UPDATED_TIMESTAMP TIMESTAMP
);

create TABLE DEMO_DB_USER99.PUBLIC.WEEKLY_EXPENSE_STG (EXPENSE VARCHAR);

create TABLE DEMO_DB_USER99.PUBLIC.MTL_JOB_HISTORY (
	PROJECT_ID NUMERIC(38,0),
	PROJECT_NAME VARCHAR,
	ENV_NAME VARCHAR,
	JOB_ID NUMERIC(38,0),
	JOB_NAME VARCHAR,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	JOB_STATUS VARCHAR,
	RUN_ID INT
);